- job:
    name: qinling-tempest
    parent: devstack-tempest
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/python-qinlingclient
      - openstack/qinling
      - openstack/tempest
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*
      - ^qinling/tests/unit/.*$
      - ^releasenotes/.*$
    pre-run: playbooks/pre.yaml
    post-run: playbooks/post.yaml
    vars:
      devstack_services:
        # Disable unneeded services.
        # These services are enabled in the devstack base job and are not
        # needed for qinling.
        etcd3: false
        peakmem_tracker: false
        tls-proxy: false
        g-api: false
        g-reg: false
        n-api: false
        n-api-meta: false
        n-cauth: false
        n-cond: false
        n-cpu: false
        n-novnc: false
        n-obj: false
        n-sch: false
        placement-api: false
        q-agt: false
        q-dhcp: false
        q-l3: false
        q-meta: false
        q-metering: false
        q-svc: false
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        c-api: false
        c-bak: false
        c-sch: false
        c-vol: false
        cinder: false
      devstack_plugins:
        qinling: https://git.openstack.org/openstack/qinling
      devstack_localrc:
        TEMPEST_PLUGINS: '/opt/stack/qinling'
      tox_envlist: all-plugin
      tempest_test_regex:  '^(qinling_tempest_plugin.)'
      # Set tempest concurrency to qinling's default number of replicas in a
      # deployment to avoid tests failing of no avaliable pod.
      tempest_concurrency: 3

- project:
    check:
      jobs:
        - qinling-tempest:
            voting: false
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - openstack-tox-lower-constraints
